{% set name = "opentelemetry-exporter-zipkin" %}
{% set version = "1.33.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_zipkin-{{ version }}.tar.gz
  sha256: 9cedfb5d4c224734111f3819de9b85f1e6713683a7a369583c4f5bf1ed3c9cb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-exporter-zipkin-json ==1.33.1
    - opentelemetry-exporter-zipkin-proto-http ==1.33.1

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.zipkin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-zipkin
  summary: Zipkin Span Exporters for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
