{% set name = "opentelemetry-exporter-zipkin" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_zipkin-{{ version }}.tar.gz
  sha256: 41a08d81e13a12759b84aa3132f51c1a0081d2d435424a7f8ae429f6e2991505

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-exporter-zipkin-json ==1.26.0
    - opentelemetry-exporter-zipkin-proto-http ==1.26.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.zipkin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-zipkin
  summary: Zipkin Span Exporters for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
