{% set name = "opentelemetry-exporter-zipkin" %}
{% set version = "1.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_zipkin-{{ version }}.tar.gz
  sha256: 19b07acfc4e7d4c039fe406460c81355b6b55822e05668ec1bbc1437492090bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-exporter-zipkin-json ==1.35.0
    - opentelemetry-exporter-zipkin-proto-http ==1.35.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.zipkin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-zipkin
  summary: Zipkin Span Exporters for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
